### ISSUE TITLE
ModuleNotFoundError: No module named 'fm.losses'

### ISSUE THREAD

**Issue by LiRunyi2001** [yuanzhi-zhu/OFTSR#1]
Hi there, I am trying to run the inferencce code:
```
python sample_fm.py --opt configs/ir_fm_imagenet.yml \
        --overrides \
        sample.pre_train_model=ckpts/sr_bicubic-sf4-guided_unet-sigma0.2-bs32-loss_l1-lr1e-04-ImageNet-checkpoint_10.pth \
        dataset.val_path='./val_data/imagenet_val_100' \
        sample.num_sample=100 \
        ir.sigma_y=0. \
        ir.sigma_pertubation=0.2 \
        fm_model.use_cond=true
```

and it turns out the output:
```
Traceback (most recent call last):
  File "OFTSR/sample_fm.py", line 10, in <module>
    from fm.utils import (parse_args_and_config,
  File "OFTSR/fm/__init__.py", line 1, in <module>
    from .flow_matching import FM
  File "OFTSR/fm/flow_matching.py", line 12, in <module>
    from fm.losses import get_flow_loss_fn
ModuleNotFoundError: No module named 'fm.losses'
```
It seems that there do not exits a file named losses.py in ./fm/, maybe the code is missing?

**Comment by yuanzhi-zhu** [comment]
@LiRunyi2001  thank you for your interest in this work, I've updated the repo.
could you please try again

**Comment by LiRunyi2001** [comment]
It works now, thanks!

**Comment by yuanzhi-zhu** [comment]
Don't hesitate if you have any questions ;p

**Comment by LiRunyi2001** [comment]
Hi there, I also wonder when will the training code be open? Thanks a lot!

**Comment by yuanzhi-zhu** [comment]
We have update the training code for the first stage rectified flow training.
The distillation code will be released soon

**Comment by YangDan123** [comment]
Very inspiring work! Do you have plan to upload the distillation code in near future?

**Comment by yuanzhi-zhu** [comment]
> Very inspiring work! Do you have plan to upload the distillation code in near future?

@YangDan123 Thank you for your interests, that's definitely in the plan!
